<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\LinkForge.Application\LinkForge.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\LinkForge.Infrastructure\LinkForge.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\LinkForge.Persistence\LinkForge.Persistence.csproj" />
  </ItemGroup>

</Project>
