<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b4e215d4-dce1-41f8-9a50-1f06c21ee762</UserSecretsId>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Application\EventRegistrationSystem.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\EventRegistrationSystem.Persistence\EventRegistrationSystem.Persistence.csproj" />
    <ProjectReference Include="..\Infrastructure\EventRegistrationSystem.Infrastructure\EventRegistrationSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
